#!/usr/bin/env python3
"""Regenerate or verify Scout's Linux CPython 3.12 hash-locked wheels."""

import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "tests/requirements-schema-linux-py312.in"
DEFAULT_OUTPUT = ROOT / "tests/requirements-schema-linux-py312.txt"

def normalized(value):
    return re.sub(r"[-_.]+", "-", value).lower()

def requirements(path):
    entries = []
    for line in path.read_text().splitlines():
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        if "==" not in value:
            raise ValueError(f"requirement must be exactly pinned: {value}")
        name, version = value.split("==", 1)
        entries.append((name, version))
    return entries

def download(seed, destination):
    subprocess.run([sys.executable, "-m", "pip", "download", "--disable-pip-version-check",
                    "--only-binary=:all:", "--no-deps", "--platform", "manylinux_2_17_x86_64",
                    "--implementation", "cp", "--python-version", "312", "--abi", "cp312",
                    "--dest", str(destination), "--requirement", str(seed)], check=True)

def select_wheel(wheel_dir, name, version):
    matches = []
    wanted_name, wanted_version = normalized(name), normalized(version)
    for path in wheel_dir.glob("*.whl"):
        parts = path.name.split("-")
        if len(parts) >= 2 and normalized(parts[0]) == wanted_name and normalized(parts[1]) == wanted_version:
            matches.append(path)
    if len(matches) != 1:
        raise RuntimeError(f"expected one wheel for {name}=={version}, found {[item.name for item in matches]}")
    return matches[0]

def render(seed, wheel_dir):
    lines = ["# Hash-locked Linux x86_64 / CPython 3.12 schema-test environment.",
             "# Generated by tests/scripts/refresh_schema_lock.py; do not edit hashes manually."]
    for name, version in requirements(seed):
        wheel = select_wheel(wheel_dir, name, version)
        digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
        lines += [f"{name}=={version} \\", f"    --hash=sha256:{digest}"]
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--wheel-dir", type=Path, help="Use an existing wheel directory instead of downloading")
    parser.add_argument("--check", action="store_true", help="Fail when regeneration differs from the committed lock")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="scout-schema-lock-") as temp_name:
        wheel_dir = args.wheel_dir or Path(temp_name)
        if args.wheel_dir is None:
            download(args.input, wheel_dir)
        generated = render(args.input, wheel_dir)
    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            raise SystemExit(f"schema lock is stale: regenerate {args.output}")
        print(f"Schema lock verified: {args.output}")
    else:
        args.output.write_text(generated)
        print(f"Schema lock refreshed: {args.output}")

if __name__ == "__main__":
    main()
